openapi: 3.0.0
info:
  title: Supply Chain Tracker API
  version: 1.0.0
  description: API for tracking supply chain items and their events

servers:
  - url: /api
    description: Default server

paths:
  /items:
    get:
      summary: Get all items
      description: Retrieve a list of all supply chain items
      responses:
        '200':
          description: List of items retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
        '500':
          description: Internal server error
          
    post:
      summary: Create a new item
      description: Add a new item to the supply chain
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - color
                - price
              properties:
                name:
                  type: string
                color:
                  type: string
                price:
                  type: number
                  format: float
      responses:
        '201':
          description: Item created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
        '400':
          description: Invalid input
        '500':
          description: Internal server error

  /items/{id}:
    get:
      summary: Get item by ID
      description: Retrieve a specific item by its ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Item found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
        '404':
          description: Item not found
        '500':
          description: Internal server error

  /items/{id}/events:
    get:
      summary: Get events for an item
      description: Retrieve all events associated with a specific item
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Events retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
        '404':
          description: Item not found
        '500':
          description: Internal server error
          
    post:
      summary: Create new event
      description: Create a new event for a specific item
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - location
                - custodian
              properties:
                location:
                  type: string
                  description: Location where the event occurred
                custodian:
                  type: string
                  description: Person or entity responsible for the item
      responses:
        '201':
          description: Event created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '404':
          description: Item not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /items/{id}/events/last:
    get:
      summary: Get latest event for an item
      description: Retrieve the most recent event for a specific item
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the item
      responses:
        '200':
          description: Latest event retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '404':
          description: Item not found or no events exist
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

components:
  schemas:
    Item:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        color:
          type: string
        price:
          type: number
          format: float
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        events:
          type: array
          items:
            $ref: '#/components/schemas/Event'
      required:
        - id
        - name
        - color
        - price
        - createdAt
        - updatedAt

    Event:
      type: object
      properties:
        id:
          type: integer
          format: int64
        itemId:
          type: integer
          format: int64
        location:
          type: string
        custodian:
          type: string
        createdAt:
          type: string
          format: date-time
      required:
        - id
        - itemId
        - location
        - custodian
        - createdAt 